language: go
go: 1.13.x

install: echo "success!"
script: echo "success!"

deploy:
- provider: script
  skip_cleanup: true
  script: ./release.sh
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = linux

- provider: script
  skip_cleanup: true
  script: export DEPLOY_TO=production && cd docs && bash deploy.sh
  on:
    branch: master

- provider: script
  skip_cleanup: true
  script: export DEPLOY_TO=staging && cd docs && bash deploy.sh
  on:
    branch: niko-dev