language: go
python: "3.6"
go: 1.13.x

install: echo "success!"
script: echo "success!"

deploy:
- provider: script
  skip_cleanup: true
  # TODO: update Homebrew tap
  script: ./release.sh
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = linux