language: go
go: 1.13.x

install: echo "success!"
script: echo "success!"

before_deploy: 
- curl -LO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl
- chmod +x ./kubectl
- sudo mv ./kubectl /usr/local/bin/kubectl
- curl -fsSL https://clis.cloud.ibm.com/install/linux | sh
- ibmcloud plugin install container-registry
- ibmcloud plugin install kubernetes-service

deploy:
- provider: script
  cleanup: false
  script: ./release.sh
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = linux

- provider: script
  cleanup: false
  script: export DEPLOY_TO=production && cd docs && bash deploy.sh
  on:
    branch: master

- provider: script
  cleanup: false
  script: export DEPLOY_TO=staging && cd docs && bash deploy.sh
  on:
    branch: niko-dev