language: go
go: 1.13.x

install: echo "success!"
script: echo "success!"

before_deploy: 
- curl -sL https://ibm.biz/idt-installer | bash
deploy:
- provider: script
  skip_cleanup: true
  script: ./release.sh
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = linux

- provider: script
  skip_cleanup: true
  script: export DEPLOY_TO=production && cd docs && ./deploy.sh
  on:
    branch: master