language: go
go: 1.13.x

services:
- docker

before_install:
- mkdir protoc_3.3
- cd protoc_3.3
- wget wget https://github.com/google/protobuf/releases/download/v3.3.0/protoc-3.3.0-linux-x86_64.zip
- chmod 775 protoc-3.3.0-linux-x86_64.zip
- unzip protoc-3.3.0-linux-x86_64.zip
- export PATH=$PATH:$PWD/bin/protoc

install:
- curl -sL https://ibm.biz/idt-installer | bash
- echo "" > trainer/.env
- cd trainer
- make setup_classification
- make setup_object_detection
- make build

jobs:
  include:
    - stage: test
      script: cd trainer && make run_classification
    - stage: test
      script: cd trainer && make run_localization

    # - stage: deploy
    #   deploy:
    #   - provider: script
    #     skip_cleanup: true
    #     script: ./release.sh
    #     on:
    #       tags: true
    #       condition: $TRAVIS_OS_NAME = linux

    #   - provider: script
    #     skip_cleanup: true
    #     script: export DEPLOY_TO=production && cd docs && ./deploy.sh
    #     on:
    #       branch: master